In [3]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

#### Ejercicio 1

Supongamos que tenemos el dataframe dfB, y queremos imputar o asignar el valor de la **mediana** a los valores nulos (nan) de todas sus columnas.   
Al imputador ll√°melo imputador1 y guarde los resultados ya transformados en un DataFrame denominado dfB_Transformado.

In [4]:
dfB=pd.DataFrame([[1,5,4,3],[np.nan,3,2,np.nan],[7,np.nan,0,4],[4,2,4,1],[3,0,np.nan,8],[2,7,5,4]])
dfB.columns=['col1','col2','col3','col4']
dfB

   col1  col2  col3  col4
0   1.0   5.0   4.0   3.0
1   NaN   3.0   2.0   NaN
2   7.0   NaN   0.0   4.0
3   4.0   2.0   4.0   1.0
4   3.0   0.0   NaN   8.0
5   2.0   7.0   5.0   4.0

In [13]:
imputador1 = SimpleImputer(missing_values= np.nan, strategy = 'median')
imputador1.fit(dfB)
transformado=imputador1.transform(dfB)
dfB_Transformado= pd.DataFrame(transformado, columns = dfB.columns)
dfB_Transformado

   col1  col2  col3  col4
0   1.0   5.0   4.0   3.0
1   3.0   3.0   2.0   4.0
2   7.0   3.0   0.0   4.0
3   4.0   2.0   4.0   1.0
4   3.0   0.0   4.0   8.0
5   2.0   7.0   5.0   4.0

#### Ejercicio 2  

Dado el DataFrame dfC, impute la mediana de cada columna a los valores que tienen valor -1. Al imputador ll√°melo imputador2 y guarde los resultados en un nuevo dataFrame denominado dfC_Transformado

In [14]:
dfC=pd.DataFrame([[3,7,-1,0],[2,-1,5,4],[0,0,0,0],[-1,5,4,2],[2,6,8,1],[2,1,3,2]])
dfC.columns=['A','B','C','D']
dfC

   A  B  C  D
0  3  7 -1  0
1  2 -1  5  4
2  0  0  0  0
3 -1  5  4  2
4  2  6  8  1
5  2  1  3  2

In [19]:
imputador2 = SimpleImputer(missing_values=-1,strategy='median')
imputador2.fit(dfC)
c_transformado= imputador2.transform(dfC)
dfC_Transformado = pd.DataFrame(c_transformado, columns = dfC.columns)
dfC_Transformado

     A    B    C    D
0  3.0  7.0  4.0  0.0
1  2.0  5.0  5.0  4.0
2  0.0  0.0  0.0  0.0
3  2.0  5.0  4.0  2.0
4  2.0  6.0  8.0  1.0
5  2.0  1.0  3.0  2.0

#### Ejercicio 3  
Vamos a complicarla un poco:  
    

Dado el DataFrame dfC: 

- En las columnas A y C, impute a los valores -1, el promedio. Llame a este imputador imputador_prom
- En las columnas B y D impute a los valores -1 la mediana. Llame a este imputador imputador_mediana

Guarde los resutados en un nuevo DataFrame denominado dfC_Transformado2

In [40]:
AyC=dfC[['A','C']]
ByD = dfC [['B','D']]

   B  D
0  7  0
1 -1  4
2  0  0
3  5  2
4  6  1
5  1  2

In [41]:
imputador_prom = SimpleImputer(missing_values=-1,strategy='mean')
imputador_prom.fit(AyC)
transformado1 = imputador_prom.transform(AyC)
df_AyC= pd.DataFrame(transformado1, columns= AyC.columns)

In [42]:
imputador_mediana = SimpleImputer(missing_values=-1,strategy='median')
imputador_mediana.fit(ByD)
transformado2 = imputador_mediana.transform(ByD)
df_ByD= pd.DataFrame(transformado2, columns= ByD.columns)

In [47]:
dfC_Transformado2= pd.concat([df_AyC,df_ByD], axis=1)
dfC_Transformado2

     A    C    B    D
0  3.0  4.0  7.0  0.0
1  2.0  5.0  5.0  4.0
2  0.0  0.0  0.0  0.0
3  1.8  4.0  5.0  2.0
4  2.0  8.0  6.0  1.0
5  2.0  3.0  1.0  2.0

#### Ejercicio 4

Supongamos que tenemos un DataFrame como el dfD:

In [48]:
dfD=pd.DataFrame([[3,2,'Si'],[np.nan,6,'No'],[5,8,'Si'],[0,np.nan,'Si'],[np.nan,4,'No'],[6,6,np.nan],[4,12,'No'],[2,9,np.nan]])
dfD.columns=['x1','x2','x3']
dfD

    x1    x2   x3
0  3.0   2.0   Si
1  NaN   6.0   No
2  5.0   8.0   Si
3  0.0   NaN   Si
4  NaN   4.0   No
5  6.0   6.0  NaN
6  4.0  12.0   No
7  2.0   9.0  NaN

Observe que la variable x3 no es num√©rica, sino categ√≥rica.

Queremos imputar el promedio en las columnas num√©ricas y la moda en las columnas categ√≥ricas (esto es un problema bien t√≠pico de ML).  Queremos el resultado en un √∫nico DataFrame que se llame dfD_Transformado.

In [49]:
Numer= dfD[['x1','x2']]
cat= dfD[['x3']]

In [63]:
imputadornum = SimpleImputer(missing_values= np.nan, strategy= 'mean')
imputadornum.fit(Numer)
transformados = imputadornum.transform(Numer)
Df_numero= pd.DataFrame(transformados, columns= Numer.columns).round(0)

In [62]:
imputadorcat = SimpleImputer(missing_values= np.nan, strategy= 'most_frequent')
imputadorcat.fit(cat)
transformadoscat = imputadorcat.transform(cat)
Df_cat= pd.DataFrame(transformadoscat, columns= cat.columns)

In [65]:
dfD_Transformado= pd.concat([Df_numero,Df_cat],axis=1)
dfD_Transformado

    x1    x2  x3
0  3.0   2.0  Si
1  3.0   6.0  No
2  5.0   8.0  Si
3  0.0   7.0  Si
4  3.0   4.0  No
5  6.0   6.0  No
6  4.0  12.0  No
7  2.0   9.0  No