In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [3]:
ls

 El volumen de la unidad C no tiene etiqueta.
 El n£mero de serie del volumen es: 70CC-A66C

 Directorio de C:\Users\Alumno\clase 4-05

04/05/2022  22:21    <DIR>          .
04/05/2022  22:21    <DIR>          ..
04/05/2022  20:17    <DIR>          .ipynb_checkpoints
04/05/2022  22:21            72.138 Wine quality.ipynb
               1 archivos         72.138 bytes
               3 dirs  34.371.641.344 bytes libres

In [5]:
cd ..

C:\Users\Alumno

In [6]:
df= pd.read_csv('winequality-white.csv', sep=';')
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [7]:
df.quality.unique()

array([6, 5, 7, 8, 4, 3, 9], dtype=int64)

In [8]:
train,test= train_test_split(df, test_size=0.2,random_state=123)
train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
4120,7.4,0.28,0.50,12.1,0.049,48.0,122.0,0.99730,3.01,0.44,9.0,5
1169,7.5,0.14,0.34,1.3,0.055,50.0,153.0,0.99450,3.29,0.80,9.6,6
1941,6.8,0.31,0.32,7.6,0.052,35.0,143.0,0.99590,3.14,0.38,9.0,5
1971,6.3,0.41,0.30,3.2,0.030,49.0,164.0,0.99270,3.53,0.79,11.7,7
3124,6.5,0.24,0.39,17.3,0.052,22.0,126.0,0.99888,3.11,0.47,9.2,6
...,...,...,...,...,...,...,...,...,...,...,...,...
1593,8.6,0.16,0.49,7.3,0.043,9.0,63.0,0.99530,3.13,0.59,10.5,6
4060,6.4,0.41,0.01,6.1,0.048,20.0,70.0,0.99362,3.19,0.42,10.0,5
1346,7.0,0.46,0.39,6.2,0.039,46.0,163.0,0.99280,3.21,0.35,12.2,7
3454,5.8,0.54,0.00,1.4,0.033,40.0,107.0,0.98918,3.26,0.35,12.4,5
3582,6.3,0.32,0.32,1.5,0.037,12.0,76.0,0.98993,3.30,0.46,12.3,6

In [7]:
test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1088,7.4,0.20,0.37,16.95,0.048,43.0,190.0,0.99950,3.03,0.42,9.2,6
4366,5.9,0.29,0.28,3.20,0.035,16.0,117.0,0.98959,3.26,0.42,12.6,6
92,6.9,0.24,0.33,1.70,0.035,47.0,136.0,0.99000,3.26,0.40,12.6,7
2901,6.5,0.22,0.32,2.20,0.028,36.0,92.0,0.99076,3.27,0.59,11.9,7
2330,7.5,0.38,0.29,12.70,0.050,25.0,209.0,0.99860,3.25,0.59,9.3,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4189,6.4,0.21,0.21,5.10,0.097,21.0,105.0,0.99390,3.07,0.46,9.6,5
3341,7.6,0.17,0.27,4.60,0.050,23.0,98.0,0.99422,3.08,0.47,9.5,6
1055,8.6,0.26,0.41,2.20,0.049,29.0,111.0,0.99410,2.96,0.44,10.0,5
3114,6.3,0.17,0.32,4.20,0.040,37.0,117.0,0.99182,3.24,0.43,11.3,6
654,6.5,0.21,0.37,2.50,0.048,70.0,138.0,0.99170,3.33,0.75,11.4,7

In [8]:
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [9]:
x= df.drop(["quality"], axis=1)
x

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9
...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8

In [10]:
y= df.quality
y

0       6
1       6
2       6
3       6
4       6
       ..
4893    6
4894    5
4895    6
4896    7
4897    6
Name: quality, Length: 4898, dtype: int64

In [11]:
train_x,test_x,train_y,test_y= train_test_split(x,y, test_size=0.2,random_state=123)

In [12]:
train_x

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
4120,7.4,0.28,0.50,12.1,0.049,48.0,122.0,0.99730,3.01,0.44,9.0
1169,7.5,0.14,0.34,1.3,0.055,50.0,153.0,0.99450,3.29,0.80,9.6
1941,6.8,0.31,0.32,7.6,0.052,35.0,143.0,0.99590,3.14,0.38,9.0
1971,6.3,0.41,0.30,3.2,0.030,49.0,164.0,0.99270,3.53,0.79,11.7
3124,6.5,0.24,0.39,17.3,0.052,22.0,126.0,0.99888,3.11,0.47,9.2
...,...,...,...,...,...,...,...,...,...,...,...
1593,8.6,0.16,0.49,7.3,0.043,9.0,63.0,0.99530,3.13,0.59,10.5
4060,6.4,0.41,0.01,6.1,0.048,20.0,70.0,0.99362,3.19,0.42,10.0
1346,7.0,0.46,0.39,6.2,0.039,46.0,163.0,0.99280,3.21,0.35,12.2
3454,5.8,0.54,0.00,1.4,0.033,40.0,107.0,0.98918,3.26,0.35,12.4
3582,6.3,0.32,0.32,1.5,0.037,12.0,76.0,0.98993,3.30,0.46,12.3

In [12]:
modelo=DecisionTreeClassifier(random_state=123, max_depth=4)
modelo.fit(train_x,train_y)
pred_y=modelo.predict(test_x)

In [13]:
from sklearn.metrics import accuracy_score
acc= accuracy_score(test_y,pred_y)
acc

0.5418367346938775

In [14]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=20,weights="distance")
knn.fit(train_x,train_y)
predknn_y=knn.predict(test_x)
ac= accuracy_score(test_y,predknn_y)
ac

0.6071428571428571

In [16]:
pip install dtale

Requirement already satisfied: dtale in c:\users\alumno\anaconda3\lib\site-packages (2.3.0)
Requirement already satisfied: numpy in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (1.20.3)
Requirement already satisfied: dash-colorscales in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (0.0.4)
Requirement already satisfied: xlrd in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (2.0.1)
Requirement already satisfied: openpyxl in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (3.0.9)
Requirement already satisfied: matplotlib in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (3.4.3)
Requirement already satisfied: scipy in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (1.7.1)
Requirement already satisfied: dash-bootstrap-components in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (1.1.0)
Requirement already satisfied: statsmodels in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (0.12.2)
Requirement already satisfied: kaleido in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (0.2.1)
Requirement already satisfied: requests in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (2.26.0)
Requirement already satisfied: networkx in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (2.6.3)
Requirement already satisfied: plotly>=5.0.0 in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (5.7.0)
Requirement already satisfied: lz4 in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (4.0.0)
Requirement already satisfied: Flask in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (1.1.2)
Requirement already satisfied: future>=0.14.0 in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (0.18.2)
Requirement already satisfied: xarray in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (2022.3.0)
Requirement already satisfied: Flask-Compress in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (1.12)
Requirement already satisfied: et-xmlfile in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (1.1.0)
Requirement already satisfied: ppscore in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (1.2.0)
Requirement already satisfied: scikit-learn==0.24.2 in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (0.24.2)
Requirement already satisfied: squarify in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (0.4.3)
Requirement already satisfied: itsdangerous in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (2.0.1)
Requirement already satisfied: flask-ngrok in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (0.0.25)
Requirement already satisfied: strsimpy in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (0.2.1)
Requirement already satisfied: cycler in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (0.10.0)
Requirement already satisfied: dash>=2.0.0 in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (2.3.1)
Requirement already satisfied: six in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (1.16.0)
Requirement already satisfied: seaborn in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (0.11.2)
Requirement already satisfied: dash-daq in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (0.5.0)
Requirement already satisfied: missingno<=0.4.2 in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (0.4.2)
Requirement already satisfied: pandas in c:\users\alumno\anaconda3\lib\site-packages (from dtale) (1.3.4)
Requirement already satisfied: joblib>=0.11 in c:\users\alumno\anaconda3\lib\site-packages (from scikit-learn==0.24.2->dtale) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\alumno\anaconda3\lib\site-packages (from scikit-learn==0.24.2->dtale) (2.2.0)
Requirement already satisfied: dash-core-components==2.0.0 in c:\users\alumno\anaconda3\lib\site-packages (from dash>=2.0.0->dtale) (2.0.0)
Requirement already satisfied: dash-table==5.0.0 in c:\users\alumno\anaconda3\lib\site-packages (from dash>=2.0.0->dtale) (5.0.0)
Requirement already satisfied: dash-html-components==2.0.0 in c:\users\alumno\anaconda3\lib\site-packages (from dash>=2.0.0->dtale) (2.0.0)
Requirement already satisfied: Jinja2>=2.10.1 in c:\users\alumno\anaconda3\lib\site-packages (from Flask->dtale) (2.11.3)
Requirement already satisfied: click>=5.1 in c:\users\alumno\anaconda3\lib\site-packages (from Flask->dtale) (8.0.3)
Requirement already satisfied: Werkzeug>=0.15 in c:\users\alumno\anaconda3\lib\site-packages (from Flask->dtale) (2.0.2)
Requirement already satisfied: colorama in c:\users\alumno\anaconda3\lib\site-packages (from click>=5.1->Flask->dtale) (0.4.4)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\alumno\anaconda3\lib\site-packages (from Jinja2>=2.10.1->Flask->dtale) (1.1.1)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\alumno\anaconda3\lib\site-packages (from plotly>=5.0.0->dtale) (8.0.1)
Requirement already satisfied: brotli in c:\users\alumno\anaconda3\lib\site-packages (from Flask-Compress->dtale) (1.0.9)
Requirement already satisfied: pillow>=6.2.0 in c:\users\alumno\anaconda3\lib\site-packages (from matplotlib->dtale) (8.4.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\alumno\anaconda3\lib\site-packages (from matplotlib->dtale) (1.3.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\alumno\anaconda3\lib\site-packages (from matplotlib->dtale) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\alumno\anaconda3\lib\site-packages (from matplotlib->dtale) (3.0.4)
Requirement already satisfied: pytz>=2017.3 in c:\users\alumno\anaconda3\lib\site-packages (from pandas->dtale) (2021.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\alumno\anaconda3\lib\site-packages (from requests->dtale) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\alumno\anaconda3\lib\site-packages (from requests->dtale) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\alumno\anaconda3\lib\site-packages (from requests->dtale) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\alumno\anaconda3\lib\site-packages (from requests->dtale) (2.0.4)
Requirement already satisfied: patsy>=0.5 in c:\users\alumno\anaconda3\lib\site-packages (from statsmodels->dtale) (0.5.2)
Requirement already satisfied: packaging>=20.0 in c:\users\alumno\anaconda3\lib\site-packages (from xarray->dtale) (21.0)
Note: you may need to restart the kernel to use updated packages.

In [17]:
import dtale

In [ ]:
d=dtale.show(df)
d.open_browser()

In [15]:
n_range= range(5,100)
list=[]
for n in n_range:
    knn=KNeighborsClassifier(n_neighbors=n)
    knn.fit(train_x,train_y)
    predknn_y=knn.predict(test_x)
    ac= accuracy_score(test_y,predknn_y)
    x=x+1
print(ac)

0.47346938775510206

In [16]:
n_range= range(5,100)
list=[]
for n in n_range:
    knn=KNeighborsClassifier(n_neighbors=n,weights="distance")
    knn.fit(train_x,train_y)
    predknn_y=knn.predict(test_x)
    ac= accuracy_score(test_y,predknn_y)
    x=x+1
print(ac)

0.6377551020408163

In [ ]:
list(range(0,10))